name: build-all-containers

on:
  pull_request:
  push:
    branches: [ main ]

  # Allow workflow to be manually run from the GitHub UI
  workflow_dispatch:

  # Daily build
#  schedule:
#    - cron: "0 2 * * *"

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: php81
            file: php81.Dockerfile
            arch: [ linux/amd64, linux/arm64, linux/arm/v7 ]
            tags: webguruseu/bitbucket-pipelines-phpdockerio:php81

          - name: php82
            file: php82.Dockerfile
            arch: [linux/amd64, linux/arm64, linux/arm/v7]
            tags: webguruseu/bitbucket-pipelines-phpdockerio:php82

          - name: php82
            file: php82.Dockerfile
            arch: [ linux/amd64, linux/arm64, linux/arm/v7 ]
            tags: webguruseu/bitbucket-pipelines-phpdockerio:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Debug
        run: |
          echo "is_main: -> ${{ github.ref == 'refs/heads/main' }} <-"
          echo "ref: ${{ github.head_ref }}"
      - name: Set up QEMU (required for arm build)
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ${{ matrix.file }}
          platforms: ${{ join(matrix.arch, ',') }}
          push: ${{ github.ref == 'refs/heads/main' }}
          pull: true
          tags: ${{ matrix.tags }}